id = "quakec"
name = "QuakeC"
version = "0.0.2"
schema_version = 1
authors = ["Marc Schraffenberger <marc@schraffenberger.com>"]
description = "Zed language support for the QuakeC language"
repository = "https://github.com/schraf/zed-quakec"

[grammars.quakec]
repository = "https://github.com/vkazanov/tree-sitter-quakec"
commit = "268be403609e944a45e5620c49cbbd6683b7f676"
